### ISSUE TITLE
merge local index to existing index on disk.

### ISSUE THREAD

**Issue by lhilfiker** [lhilfiker/filesystem-full-text-search-indexer#38]
**INDEX MERGE IMPLEMENTATION DESIGN**

**1. Path ID Resolution Phase**
--------------------------------
Purpose: Map local index paths to disk paths and add new paths.

Structure:
- Array of uint16_t (2 bytes per entry)
- Size matches local index path count
- Each entry maps local_index_id -> disk_path_id
- 0 indicates path not found on disk

Process:
1. Create mapping array initialized to 0
2. Read each disk path:
   - Read 2-byte length
   - Read path content
   - If match found in local paths:
     * Store disk_id at local_index position
     * Mark path as processed
3. Add remaining paths to disk
4. Update mapping array with new IDs

| local path index | mapping array | |
| ---- | ---- | ---- |
| 0 | 18 | -> local index at ID 0 is ID 18 on disk. |
| 1 | 234 | |
|...|...|...|

**2. Transaction Management Structures**
--------------------------------
A. Transaction Entry Structure:
```
Status (1 byte):
  0 = Planned
  1 = In Progress
  2 = Completed

Index Type (1 byte):
  Identifies target index file

Location (size_t):
  Byte position or 5-bit word position

Backup ID (size_t):
  Links to backup if needed

Operation Type (1 bit):
  0 = Move
  1 = Write

Content Length (size_t):
  Size of operation data

Content (variable):
  Operation-specific data
```

B. Backup Entry Structure:
```
Backup ID (size_t)
Index Type (1 byte)
Start Location (size_t)
End Location (size_t)
Content Length (size_t)
Content (variable)
```

C. Insertion Record Structure:
```
Index Type (1 byte)
Start Position (size_t)
Move Size (size_t)
```

**3. Word Processing Phase**
--------------------------------
Process:
1. Parallel traverse disk and local word indexes
2. For existing words:
   - Check reversed block
   - Check additional blocks
   - Add missing path IDs
   - Create transactions for:
     * Direct writes if space available
     * New additional block allocations
     * Additional ID updates

3. For new words:
   - Create insertion records (words and reversed)
   - Calculate space requirements
   - Generate transactions for:
     * Word insertion
     * Reversed block creation
     * Additional block allocation if needed
   - Update offset counters

**4. Transaction Generation Phase**
--------------------------------
1. File Size Operations:
   - Calculate final sizes
   - Generate resize transactions
   - Order by index type

2. Move Operations:
   - Process insertion records back-to-front
   - Calculate cumulative offsets
   - Generate move transactions
   - Include multi-insertion spacing

**5. Backup Creation Phase**
--------------------------------
Process:
-> Not decided yet.
1. Create backup entries
2. Link backups to transactions
-> May change

**6. Execution Phase**
--------------------------------
Process:
1. Write transaction list to disk
2. Mark first transaction as started
3. For each transaction:
   - Write "In Progress" status
   - Execute operation
   - Sync affected index files
   - Write "Completed" status
   - Mark next transaction
4. After completion:
   - Verify final state
   - Remove transaction file
   - Remove backup files

**7. Recovery Handling**
--------------------------------
Detection:
- Transaction file presence indicates interrupted operation
- Check first entry status for Started status (If it is no status, we can delete the transaction file)

Recovery Process:
1. Read transaction list
2. Identify last completed operation
3. For in-progress operation:
   - Check operation type
   - Verify data state
   - Restore from backup if needed
   - Redo transaction if possible(all non move operations)
4. Resume execution from last verified point

**8. Safety Measures**
--------------------------------
- Sync disk after status changes
- Maintain backup until full completion
- Track system resources

This design ensures:
- Data integrity during updates
- Recovery from interruptions
- Minimal data movement

**8. Future**
--------------------------------
- Possibility to disable and to just do direct write
- Detecting deleted words in file and removing them.

### TODO
- [x] Cleanup. Seperate Functions in index:add for better readability and comment the code properly
- [x] words_f: save as vector instead of an array in memory
- [x] code for merging a new word into the index, creating word transaction, e.g reversed or additional.(reuse code when cleanup is done)
- [x] append remaining words at the end. reuse most code of cleanup
- [ ] create transactions list
